### ISSUE TITLE
v4.8.0 - ColoredRecord does not set asctime property.

### ISSUE THREAD

**Issue by colinburroughs** [borntyping/python-colorlog#101] opened 2021-04-13 10:29 UTC
When I have a defined formatter which includes acstime, the ColoredRecord fails to set the asctime property.
```
...
'simple': {
    '()': 'colorlog.ColoredFormatter',
    'format': '%(log_color)s%(levelname)-8s %(asctime)s - %(message)s'
}
...
```

```
class MyHandler(logging.Handler):
    def emit(self, record: logging.LogRecord):
        _datetime = datetime=record.asctime
        print(_datetime)
```

**Comment by borntyping** [comment] 2021-04-13 12:57
I'm not clear what the problem is here. Are you able to include an example I could run to reproduce the issue?

**Comment by borntyping** [comment] 2021-06-14 17:18
This _might_ be fixed in the current version of colorlog, which changed so that `Formatter.format` (which sets `record.asctime`) isn't replaced. I'd recommend not relying on `record.asctime` in handlers though, as they should work with any Formatter instance they are given.

**Closed by borntyping** 2021-06-14 17:18 UTC
