### ISSUE TITLE
Product description on pypi is not formatted

### ISSUE THREAD

**Issue by WoLpH** [borntyping/python-colorlog#67] opened 2019-02-09 14:35 UTC
While the readme over here looks just fine, the version on Pypi is really unreadable.

https://pypi.org/project/colorlog/

**Comment by borntyping** [comment] 2019-02-13 12:49
I've noticed this but not really sure what the problem is. With other projects I have, the setup.py metadata describing the file as markdown works and it renders correctly: https://github.com/borntyping/python-colorlog/blob/master/setup.py#L8-L9

**Comment by WoLpH** [comment] 2019-02-13 13:22
It might be related to the packages in your environment: https://packaging.python.org/guides/making-a-pypi-friendly-readme/#including-your-readme-in-your-package-s-metadata

Try: `python3 -m pip install --user --upgrade setuptools wheel twine`

**Comment by GhostofGoes** [comment] 2019-02-16 04:17
`setuptools` has to be at least version 38.6, so upgrading the packages in your environment then pushing should fix the formatting.

**Comment by hartwork** [comment] 2020-07-22 17:04
Hi!

There is two pieces to this: (1) marking the description as markdown and (2) requiring recent enough setuptools in `setup_requires`. (1) is already done at https://github.com/borntyping/python-colorlog/blob/07fe00e5b4c71265242876a964e261225ea7acff/setup.py#L9 

Looking at [colorlog's PyPI page](https://pypi.org/project/colorlog/) today, (2) seems to no longer be a problem in practice, probably because the person who uploaded used recent enough setuptools. For a clean fix, I suggest to apply something like https://github.com/hartwork/surrogates/blob/ad2991d5e628d3c66eeb51e9c6bf5b3f11b11596/setup.py#L21-L23 nevertheless to have a stable full fix.

What do you think?

**Comment by borntyping** [comment] 2020-07-23 15:36
Updated and released as version 4.2.1. Thanks for the help all!

https://github.com/borntyping/python-colorlog/releases/tag/v4.2.1
https://github.com/borntyping/python-colorlog/commit/c06583f39476a62664211508f65d4f33a5b0eee5

**Closed** 2020-07-23 15:36 UTC
