### ISSUE TITLE
Failed to add color to log

### ISSUE THREAD

**Issue by AtomAsking** [borntyping/python-colorlog#129] opened 2023-08-01 07:50 UTC
```python
"""
Structured JSON logging to File and Coloring Python log output.

pip install python-json-logger
pip install colorlog
"""
import inspect
import logging
import sys
from datetime import datetime, timedelta

import colorlog
from pythonjsonlogger import jsonlogger


class CustomLogger:
    _instances = {}  # singleton instances

    def __new__(cls, name=None, level=logging.INFO):
        if name is None:
            name = inspect.getmodule(inspect.stack()[1][0]).__name__
        if name not in cls._instances:
            cls._instances[name] = super().__new__(cls)
            cls._instances[name]._name = name
        return cls._instances[name]

    def __init__(self):
        if not hasattr(self, 'logger'):
            instance_name = getattr(self, '_name', None)
            print(instance_name)
            # logger
            self.logger = logging.getLogger(instance_name)
            self.logger.setLevel(logging.DEBUG)

            # StreamHandler
            stdout_handle = colorlog.StreamHandler(stream=sys.stdout)
            stdout_handle.setLevel(level=logging.DEBUG)

            # FileHandler
            file_handle = logging.FileHandler("/tmp/log.json",
                                              mode="a",
                                              encoding="utf-8")
            file_handle.setLevel(level=logging.WARNING)

            # Formatter
            logging.Formatter.converter = self.cst_timetuple
            stdout_fmt = colorlog.ColoredFormatter(
                fmt="%(blue)s%(filename)s:%(lineno)d%(reset)s "
                    "| %(name)s "
                    "| %(white)s%(asctime)s%(reset)s "
                    "| %(log_color)s%(levelname)s%(reset)s "
                    ">>> %(log_color)s%(message)s%(reset)s",
                datefmt='%Y-%m-%dT%H:%M:%S+08:00')
            json_fmt = jsonlogger.JsonFormatter(
                fmt=
                "%(name)s %(asctime)s %(levelname)s %(filename)s %(lineno)s %(process)d %(message)s",
                rename_fields={
                    "levelname": "severity",
                    "asctime": "timestamp"
                },
                datefmt="%Y-%m-%dT%H:%M:%S+08:00",
            )

            # setFormatter
            stdout_handle.setFormatter(stdout_fmt)
            file_handle.setFormatter(json_fmt)

            # addHandler
            self.logger.addHandler(stdout_handle)
            self.logger.addHandler(file_handle)

            # Prevent messages from propagating to the root logger
            self.logger.propagate = False

            # Assign the excepthook to the handler
            sys.excepthook = self.handle_unhandled_exception

    @staticmethod
    def cst_timetuple(*args) -> tuple:
        """Returns a tuple representing the current time in China Standard Time (CST).
        """
        cst_time = datetime.utcnow() + timedelta(hours=8)
        return cst_time.timetuple()

    def debug(self, message):
        self.logger.debug(message)

    def info(self, message):
        self.logger.info(message)

    def warning(self, message):
        self.logger.warning(message)

    def error(self, message):
        self.logger.error(message)

    def critical(self, message):
        self.logger.critical(message)

    def handle_unhandled_exception(self, exc_type, exc_value, exc_traceback):
        """Handles unhandled exceptions by logging them as critical level messages,
        except for KeyboardInterrupt, which is re-raised.
        """
        if issubclass(exc_type, KeyboardInterrupt):
            sys.__excepthook__(exc_type, exc_value, exc_traceback)
            return
        # Create a critical level log message with info from the except hook.
        self.logger.critical("Unhandled exception",
                             exc_info=(exc_type, exc_value, exc_traceback))


if __name__ == '__main__':
    logger = CustomLogger()
    # Generate Log
    logger.debug("This is debug message.")
    logger.info("This is info message.")
    logger.warning("This is warning message.")
    logger.error("This is error message.")
    logger.critical("This is critical message.")
```
Import and use in other py files, it is found that the log has no color.
```python
from utilities.logging_utils import CustomLogger
logger = CustomLogger()
print(logger.__dict__)
logger.debug("This Message None Color.")
```
I tried to use the `force_color` attribute to set it, but it still doesn't work.
I think this is a bug, which is contrary to the original intention of this package, looking forward to your reply. Thanks

**Comment by borntyping** [comment] 2023-08-01 22:17
I can't reproduce this bug running the code you've provided. Are you able to create a simpler example that reproduces the bug you think you're seeing?

![image](https://github.com/borntyping/python-colorlog/assets/249351/94b42ee8-5f7b-46f2-aca7-53aa5d8dc243)

**Comment by borntyping** [comment] 2023-08-01 22:21
Do you maybe have `NO_COLOR` set in your environment variables? Do you get colour output if you run the [example.py](https://github.com/borntyping/python-colorlog/blob/main/doc/example.py) script from the docs?

**Comment by AtomAsking** [comment] 2023-08-02 01:49
@borntyping First of all thank you for your quick response. 
As you can see above, I have a `CustomLogger` tool Class (`utilities.logging_utils.py`), and I want to import this module for use in other packages. For example, I import in `foo/bar.py` using.
```
.
├── utilities
│           │   
│         └── logging_utils.py
└── foo
          └── bar.py
```

```python
from utilities.logging_utils import CustomLogger

logger = CustomLogger()

logger.debug("test color")
```
I found that `test color` Message has no color, I did not set `NO_COLOR` in my environment variables, I executed `python utilities/logging_utils.py` to print the color is normal, but I executed `python foo/bar.py` then the output logs have no color, and the above is all my code. 
This may indeed not be a bug, because I also found another problem at the same time, my `json` logs are not saved, the json logs are only logged when `python utilities/logging_utils.py`. I'm still troubleshooting what the problem is.

**Comment by borntyping** [comment] 2023-12-02 16:48
Closing this for now. Feel free to reopen it if you can provide a reproducible example :)

**Closed by borntyping** 2023-12-02 16:48 UTC
